[project]
name = "django-channels-messaging"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "channels[daphne]>=4.2.2",
  "django==4.2",
  "django-structlog>=9.1.1",
  "websockets>=15.0.1",
]
